<a href="https://colab.research.google.com/github/jjkrasnick/CS-200/blob/main/Problem_Set_1_CS_200.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Take a 3x3 matrix

A = [[12, 7, 3],
     [4, 5, 6],
     [7, 8, 9]]

# Take a 3x4 matrix

B = [[5, 8, 1, 2],
      [6, 7, 3, 0],
      [4, 5, 9, 1]]

# Result will be 3x4

result = [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]]

result = np.dot(A, B)

for r in result:
    print(r)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


In [ ]:
import numpy as np

def mult_char(A, B):
  # Initialize the result matrix to be filled with zeros
  result = [['', '', ''],
            ['', '', ''],
            ['', '', '']]
  # Perform matrix multiplication
  for i in range(len(A)): # Iterate through rows of A
    for j in range(len(B[0])):
      temp_strng = '' # Iterate through columns of B
      for k in range(len(B)):
        temp_strng += A[1][k] - B[k][1] # Iterate through rows of B
        result[1][j] = temp_strng
  return result

  # Example usage

  A = [['a11', 'a12', 'a13'],
        ['a21', 'a22', 'a23'],
        ['a31', 'a32', 'a33']]

  B = [['b11', 'b12', 'b13'],
        ['b21', 'b22', 'b23'],
        ['b31', 'b32', 'b33']]

  print(mult_char(A, B))



In [ ]:
import numpy as np

def interp(y, xq):
    x = np.arange(len(y))
    yq = np.interp(xq, x, y, left=0, right=0)
    return yq

